#!/bin/sh

# necessary to make chrome pick up the proxy settings stored in gconf.
export DESKTOP_SESSION=cinnamon

# avoid SSH_AUTH_SOCK errors
# eval $(keychain --eval --agents ssh id_rsa)
eval $(ssh-agent)

#background color
xsetroot -solid "#4f3d61"

# XTerm is being weird with Xresources, use urxvt instead
# export TERMINAL=urxvt

# Start wmi3
exec i3
