" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" ================ General Config ====================
set number                      "Line numbers are good
set backspace=indent,eol,start  "Allow backspace in insert mode
set clipboard=unnamedplus       "use system clipboard by default
set history=1000                "Store lots of :cmdline history
set showcmd                     "Show incomplete cmds down the bottom
set showmode                    "Show current mode down the bottom
set autoread                    "Reload files changed outside vim
set foldmethod=indent           "Fold files based on indentation
set hidden                      "let buffer be open with no window 
let mapleader=" "               "Change leader to spacebar

autocmd FileType qf setlocal wrap

" ===============  Plugin Configuration ================ 
filetype plugin on
" Golden Ratio
let g:golden_ratio_exclude_nonmodifiable = 1
let g:golden_ratio_autocommand = 0
" MRU
let MRU_Max_Entries = 1000
" NerdTree
let NERDTreeDirArrows = 1
let g:NERDTreeWinSize = 50
let NERDTreeQuitOnOpen=1
" CoC Start
let g:coc_global_extensions=['coc-tsserver', 'coc-tslint-plugin', 'coc-stylelint', 'coc-styled-components', 'coc-prettier', 'coc-jest']
" Give more space for displaying messages.
set cmdheight=2

" Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
" delays and poor user experience.
set updatetime=300

" Don't pass messages to |ins-completion-menu|.
set shortmess+=c

" Use tab for trigger completion with characters ahead and navigate.
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config.
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Use <c-space> to trigger completion.
if has('nvim')
  inoremap <silent><expr> <c-space> coc#refresh()
else
  inoremap <silent><expr> <c-@> coc#refresh()
endif

" Use <cr> to confirm completion, `<C-g>u` means break undo chain at current
" position. Coc only does snippet and additional edit on confirm.
" <cr> could be remapped by other vim plugin, try `:verbose imap <CR>`.
if exists('*complete_info')
  inoremap <expr> <cr> complete_info()["selected"] != "-1" ? "\<C-y>" : "\<C-g>u\<CR>"
else
  inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
endif

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction

" Highlight the symbol and its references when holding the cursor.
autocmd CursorHold * silent call CocActionAsync('highlight')

augroup mygroup
  autocmd!
  " Setup formatexpr specified filetype(s).
  autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
  " Update signature help on jump placeholder.
  autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
augroup end

" Add `:Format` command to format current buffer.
command! -nargs=0 Format :call CocAction('format')

" Add `:Fold` command to fold current buffer.
command! -nargs=? Fold :call     CocAction('fold', <f-args>)

" Add `:OR` command for organize imports of the current buffer.
command! -nargs=0 OR   :call     CocAction('runCommand', 'editor.action.organizeImport')

" Enable scrolling in floating windows
inoremap <nowait><expr> <C-f> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(1, 1)\<cr>" : "\<Right>"
inoremap <nowait><expr> <C-b> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(0, -1)\<cr>" : "\<Left>"

augroup CloseLoclistWindowGroup
  autocmd!
  autocmd QuitPre * if empty(&buftype) | lclose | endif
augroup END
"make tab cycle autocomplete suggestions forward
inoremap <silent><expr> <Tab>
      \ pumvisible() ? "\<C-n>" : "\<TAB>"

"make shift-tab cycle autocomplete suggestions backward
inoremap <silent><expr> <S-Tab>
      \ pumvisible() ? "\<C-p>" : "\<S-TAB>"
" CoC End
" CtrlP
let g:ctrlp_custom_ignore = 'node_modules'
" let g:ctrlp_working_path_mode = 'c'
let g:ctrlp_user_command = 'find $HOME/kaggle/kaggleazure/typescript $HOME/kaggle/kaggleazure/Kaggle.Web/Views -type f -iname "*.ts*" ! -iname "*.d.ts*" && true %s'
let g:ctrlp_max_files=250000
" ================ Initialize Plugins ================
"
set runtimepath+=~/.vim/dein/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.vim/dein')
  call dein#begin('~/.vim/dein')

  " Let dein manage dein
  " Required:
  call dein#add('~/.vim/dein/repos/github.com/Shougo/dein.vim')

  " Add or remove your plugins here:
  call dein#add('morhetz/gruvbox')
  call dein#add('roman/golden-ratio')
  call dein#add('pangloss/vim-javascript')
  call dein#add('herringtondarkholme/yats.vim')
  call dein#add('scrooloose/nerdtree')
  call dein#add('yegappan/mru')
  call dein#add('kien/ctrlp.vim')
  call dein#add('tpope/vim-fugitive')
  call dein#add('tpope/vim-rhubarb')
  call dein#add('junegunn/vim-easy-align')
  if has('nvim')
      call dein#add('neoclide/coc.nvim', {'merged':0, 'rev': 'release'})
  endif

  " Required:
  " call dein#update()
  call dein#end()
  call dein#save_state()
endif

if dein#check_install()
  call dein#install()
endif

" ================ Syntax and Colors =================
"turn on syntax highlighting
syntax on
set background=dark
let g:solarized_termcolors=256
colorscheme gruvbox
set synmaxcol=500
set nocursorline
" Display tabs and trailing spaces visually
set list listchars=tab:\ \ ,trail:·
set nowrap       "Don't wrap lines
set linebreak    "Wrap lines at convenient points

" ================ Turn Off Swap Files ===============
set noswapfile
set nobackup
set nowb

" ================ Persistent Undo ===================
" Keep undo history across sessions, by storing in file.
let vimDir = '$HOME/.vim'
let &runtimepath.=','.vimDir

" Keep undo history across sessions by storing it in a file
if has('persistent_undo')
    let myUndoDir = expand(vimDir . '/undodir')
    " Create dirs
    call system('mkdir ' . vimDir)
    call system('mkdir ' . myUndoDir)
    let &undodir = myUndoDir
    set undofile
endif

" ================ Indentation ======================
filetype indent on
set autoindent
set smartindent
set smarttab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab

" ================ Folds =============================
set foldmethod=indent   "fold based on indent
set foldnestmax=4       "deepest fold is 4 levels
set nofoldenable        "dont fold by default

" ================ Completion ========================
set wildmode=list:longest
set wildmenu                "enable ctrl-n and ctrl-p to scroll thru matches
set wildignore=*.o,*.obj,*~ "stuff to ignore when tab completing
set wildignore+=log/**
set wildignore+=tmp/**

" ================ Search ============================
set incsearch       " Find the next match as we type the search
set hlsearch        " Highlight searches by default
set ignorecase      " Ignore case when searching...
set smartcase       " ...unless we type a capital

" ============== Key Bindings ========================
" Applying codeAction to the selected region.
" Example: `<leader>aap` for current paragraph
xmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>a  <Plug>(coc-codeaction-selected)
" Remap keys for applying codeAction to the current buffer.
nmap <leader>ac  <Plug>(coc-codeaction)
" buffer next/previous with leader
nnoremap <leader>bn :bn<CR>
nnoremap <leader>bp :bp<CR>
" copy current filename into system clipboard - mnemonic: (c)urrent(f)ilename
nnoremap <silent> <leader>cf :let @* = expand("%:~")<CR>
" Show all diagnostics.
nnoremap <silent><nowait> <leader>ca  :<C-u>CocList diagnostics<cr>
" Manage extensions.
nnoremap <silent><nowait> <leader>ce  :<C-u>CocList extensions<cr>
" Show commands.
nnoremap <silent><nowait> <leader>cc  :<C-u>CocList commands<cr>
" Find symbol of current document.
nnoremap <silent><nowait> <leader>co  :<C-u>CocList outline<cr>
" Search workspace symbols.
nnoremap <silent><nowait> <leader>cs  :<C-u>CocList -I symbols<cr>
" Resume latest coc list.
nnoremap <silent><nowait> <leader>cp  :<C-u>CocListResume<CR>
" Use `:CocDiagnostics` to get all diagnostics of current buffer in location list.
nmap <leader>di :CocDiagnostics<CR> 
nmap <leader>dn <Plug>(coc-diagnostic-next)
nmap <leader>dp <Plug>(coc-diagnostic-prev)
" Open CtrlP in find-all mode 
nnoremap <silent> <leader>fa :CtrlPMixed<CR>
" Fugitive Git Bindings
nnoremap <leader>fb :Git blame<CR>
nnoremap <leader>fo :GBrowse<CR>
" Open the project tree and expose current file in the nerdtree with Leader+fe
nnoremap <silent> <leader>fe :NERDTreeFind<CR>:vertical<CR>
" Open CtrlP in file-finder mode 
nnoremap <silent> <leader>ff :CtrlP<CR>
" Formatting selected code.
xmap <leader>fm  <Plug>(coc-format-selected)
nmap <leader>fm  <Plug>(coc-format-selected)
"quickfix window navigation
nnoremap <leader>j :cnext<CR>
nnoremap <leader>k :cprev<CR>
" Start interactive EasyAlign in visual mode (e.g. vipga)
xmap ga <Plug>(EasyAlign)
" Start interactive EasyAlign for a motion/text object (e.g. gaip)
nmap ga <Plug>(EasyAlign)
" GoTo code navigation.
nmap <leader>gd <Plug>(coc-definition)
nmap <leader>gy <Plug>(coc-type-definition)
nmap <leader>gi <Plug>(coc-implementation)
nmap <leader>gu <Plug>(coc-references)
" leader+gr to run GoldenRatio
nnoremap <leader>gr :GoldenRatioToggle<CR>
" leader+mr to run MRU
nnoremap <leader>mr :MRU<CR>
" Apply AutoFix to problem on the current line.
nmap <leader>qf  <Plug>(coc-fix-current)
" Symbol renaming.
nmap <leader>rn <Plug>(coc-rename)
" Run jest for current project
nnoremap <leader>tp :call  CocAction('runCommand', 'jest.projectTest')
" Run jest for current file
nnoremap <leader>tf :call  CocAction('runCommand', 'jest.fileTest', ['%'])
" Run jest for current test
nnoremap <leader>tt :call CocAction('runCommand', 'jest.singleTest')<CR>
" Init jest in current cwd, require global jest command exists
nnoremap <leader>ti :call CocAction('runCommand', 'jest.init')
"(v)im (r)eload
nmap <silent> vr :so %<CR>
" Create vertical window splits easier. 
nnoremap <silent> vv <C-w>v
" w!! to write a file as sudo
cmap w!! w !sudo tee % >/dev/null
" leader+z to toggle folds
nnoremap <leader>z za
"Clear current search highlight by double tapping //
nmap <silent> // :nohlsearch<CR>

" Move between vim split windows by using the arrow keys
nnoremap <silent> <Left> <C-w>h
nnoremap <silent> <Right> <C-w>l
nnoremap <silent> <Up> <C-w>k
nnoremap <silent> <Down> <C-w>j
" ================ Experiments =======================
