setopt histignorealldups sharehistory

# Keep 2000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=2000
SAVEHIST=2000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

#Develra Prompt
source $HOME/github/develra-dotfiles/zsh/plugins/git_prompt.zsh
local host_name="%{$fg[green]%}$(hostname)"
local path_string="%{$fg[cyan]%}%~"
local prompt_string="%{$fg[white]%} $ "
NEWLINE=$'\n'
PROMPT='${host_name}:${path_string}:$(git_prompt_string)${NEWLINE}${prompt_string}'

# path
path=(
  $path
  /opt/intellij-ce-stable/bin/
  $HOME/Stash/phoenix-sdk/third-party/protoc/
  $HOME/Stash/wulfcli/src/bin/
  $HOME/bin
  $HOME/.yarn/bin
)

# Personal Aliases
alias todo='vim ~/todo.txt'
alias scratch='vim ~/scratch.txt'
alias take='sudo chown -R $(whoami)'
alias untake='sudo chown -R root'
# -x is to not wipe out the xterm history buffer
alias c='clear -x'
alias clear='clear -x'
alias ze='vim ~/.zshrc'
alias zr='source ~/.zshrc'
alias ve='vim ~/.config/nvim/init.vim'
alias gg='git grep'
function vgg() { nvim `git grep --files-with-matches "$@"`; }
function fgg() { nvim `find . -type f -name "$@"`; }

# Devices nonsense
# connect monitor home
alias cmh='xrandr --output HDMI-1 --auto --panning 3840x2160+3840+0 --scale 1.5x1.5 --right-of eDP-1'
# connect monitor self (reset after disconnect)
alias cms='xrandr --auto'

# SSH stuffs
if [ -z "$SSH_AUTH_SOCK" ] ; then
  eval `ssh-agent -s`
  ssh-add
fi

#Kaggle stuff
alias kaggle-up='~/kaggle/kaggleazure/web/dev/up.sh --no-web --no-frontend'
alias kaggle-up-full='~/kaggle/kaggleazure/web/dev/up.sh'
alias kaggle-down='~/kaggle/kaggleazure/web/dev/down.sh'
alias kaggle-connect='docker exec -it kaggle-web-dev /bin/bash'
alias kaggle-tunnel='~/kaggle/kaggleazure/web/dev/tunnel.sh'

#RS
alias runescape='GDK_SCALE=2 ~/bin/runelite'

# Global Aliases
alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'
alias -g ......='../../../../..'

# Remap Capslock to Escape
setxkbmap -option caps:escape

# (Neo)Vim for Life
alias vi=nvim
alias vim=nvim
bindkey -v                                          # Use vi key bindings in zsh
export KEYTIMEOUT=1				                    # Reduce transition delay to .4 (default) -> .1 sec
set -o vi
export EDITOR=nvim
export VISUAL=nvim

#.Net
export DOTNET_ROOT=$HOME/dotnet
export MSBuildSDKsPath=$HOME/dotnet/sdk/$($HOME/dotnet/dotnet --version)/Sdks
export PATH=${PATH}:${HOME}/dotnet:${HOME}/.dotnet:${HOME}/.dotnet/tools:$MSBuildSDKsPath

# Bash has some nice stuff sometimes I guess
bindkey '^r' history-incremental-search-backward    # [Ctrl-r] - Search backward incrementally for a specified string. The string may begin with ^ to anchor the search to the beginning of the line.
bindkey '^[[A' history-beginning-search-backward 
bindkey '^[[B' history-beginning-search-forward

#OpenWeave toolchain
export NRF5_SDK_ROOT=${HOME}/github/openweave-tools/nRF5_SDK
export NRF5_TOOLS_ROOT=${HOME}/github/openweave-tools/nRF5-CLI
export GNU_INSTALL_ROOT=${HOME}/github/openweave-tools/gcc-arm-none-eabi-7-2018-q2-update-linux/bin
export PATH=${PATH}:${NRF5_TOOLS_ROOT}/nrfjprog

#Kaggle
export PATH=$PATH:/home/michaelaaron/kaggle/kaggleazure/web/dev

#NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# Warp Drive
export fpath=(${HOME}/bin/wd $fpath)
wd() {
  . ${HOME}/bin/wd/wd.sh
}

